name: prosto_sudoku
description: "Просто Судоку — красивая и удобная игра для тренировки мозга"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png
